<a href="https://colab.research.google.com/github/lee00206/ML_study_for_beginners/blob/main/TensorFlow_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v2/version/__init__.py'>


### **Creating Tensors**

In [5]:
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

### **Rank/Degree of Tensors**
Another word for rank is degree, these terms simply mean the number of dimensions involved in the tensor. What we created above is a *tensor of rank 0*, also known as a scalar.

In [8]:
rank1_tensor = tf.Variable(["Test", "Ok"], tf.string)
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string)


To determine the rank of a tensor we can call the following method.


In [9]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

### **Shape of Tensors**
The shape of a tensor is simply the amount of elements that exist in each dimension.<br>
To get the shape of a tensor we use the shape attribute.

In [11]:
rank2_tensor.shape  # 2 list 2 elements return TensorShape([2, 2])

TensorShape([2, 2])

### **Changing Shape**
The number of elements of a tensor is the product of the sizes of all its shapes. There are often many shapes that have the same number of elements, making it convient to be able to change the shape of a tensor.<br>
The number of elements in the reshaped tensor must match the number in the original.

In [14]:
tensor1 = tf.ones([1, 2, 3])  # tf.ones() creates a shape [1, 2, 3] tensor full of ones
                              # 1 interior list, 2 lists inside the list, each list has 3 elements
print(tensor1)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [15]:
tensor2 = tf.reshape(tensor1, [2, 3, 1])  # reshape existing data to shape [2, 3, 1]
print(tensor2)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)


In [17]:
tensor3 = tf.reshape(tensor2, [3, -1])  # -1 tells the tensor to calculate the size of the dimension in that place
                                        # this will reshape the tensor to [3, 2]
print(tensor3)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
